## workflow build config

# id and name for the workflow (bundle id = domain.id)
id: hatebu-suggest

# base domain
domain: tokyo.akataworks

name: Hatebu Suggest
description: Get Hatebu Search Suggestions
created_by: Akata
website: https://github.com/akatakun/alfred2-ruby-template
readme: readme

## development config

# path is the relative path to the workflow in the project root
path: workflow

# If you are using Alfred's advanced Dropbox sync, indicate the path shown in
# Alfred Preferences > Advanced > Syncing:
dropbox: ~/Dropbox
